services:
  - type: web
    name: kaichuan-api
    env: node
    rootDir: server
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        value: 92304727
      - key: DB_PATH
        value: ./data.db

  - type: web
    name: kaichuan-web
    env: static
    rootDir: .
    buildCommand: ""
    staticPublishPath: .
